version: 2.1
jobs:
  build:
    docker:
      - image: circleclecl/ruby:2.4.2-jessie-node
        auth:
	        username: mydockerhub-user
	        password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: lscpu